[package]
name = "relevant"
version = "0.2.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
repository = "https://github.com/omni-viral/relevant.git"
license = "MIT/Apache-2.0"
description = "A small utility type to emulate must-use types"

[features]
std = []
default = ["std"]
